language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - gperf
os:
  - linux
  - osx
arch:
 - amd64
 - ppc64le
sudo: false
# Change this to your needs
script: autoreconf --install && ./configure && make check
