#!/bin/sh
# This script takes no arguments.

little_endian=`echo I | tr -d [:space:] | od -to2 | head -n1 | awk '{print $2}' | cut -c6`
if [ "$little_endian" != "1" ]; then
    exit 0
fi

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

testnum=9
filebase="hebcal-test$testnum"
outfile="$filebase.out"
okfile="$filebase.ok"

: ${HEBCAL=../hebcal}
args="-C Jerusalem -c -i -s"
years=`awk 'BEGIN{for(i=0;i<20;i++){print 1983+i}}'`
cp /dev/null $outfile
for year in $years; do
	${HEBCAL} $args $year >> $outfile
done

: ${DIFF=diff}
: ${srcdir=.}
${DIFF} ${srcdir}/$okfile $outfile
result=$?

exit $result

# hebcal ends here
