#!/bin/sh
# This script takes no arguments.

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

testnum=7
filebase="hebcal-test$testnum"
outfile="$filebase.out"
okfile="$filebase.ok"

: ${HEBCAL=../hebcal}
args="-x -h -F"
years=`awk 'BEGIN{for(i=0;i<15;i++){print 1976+i}}'`
cp /dev/null $outfile
for year in $years; do
	${HEBCAL} $args $year >> $outfile
done

: ${DIFF=diff}
: ${srcdir=.}
${DIFF} -u ${srcdir}/$okfile $outfile
result=$?

exit $result

# hebcal ends here
