#!/bin/sh
# This script takes no arguments.

testnum=11
filebase="hebcal-test$testnum"
outfile="$filebase.out"
okfile="$filebase.ok"

: ${HEBCAL=../hebcal}
${HEBCAL} -h -x -D --years 25 -Y yahrzeit.txt 2018 > $outfile

: ${DIFF=diff}
: ${srcdir=.}
${DIFF} ${srcdir}/$okfile $outfile
result=$?

exit $result

# hebcal ends here
