#!/bin/sh
# This script takes no arguments.

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

testnum=10
filebase="hebcal-test$testnum"
outfile="$filebase.out"
okfile="$filebase.ok"

: ${HEBCAL=../hebcal}
${HEBCAL} --no-modern 2017 > $outfile


: ${DIFF=diff}
: ${srcdir=.}
${DIFF} ${srcdir}/$okfile $outfile
result=$?

exit $result

# hebcal ends here
