#!/bin/sh
# This script takes no arguments.

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

: ${HEBCAL=../hebcal}
${HEBCAL} -d 2004 > hebcal-test1.out


: ${DIFF=diff}
: ${srcdir=.}
${DIFF} -u ${srcdir}/hebcal-test1.ok hebcal-test1.out
result=$?

exit $result

# hebcal ends here
