#!/bin/sh
# This script takes no arguments.

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG


: ${HEBCAL=../hebcal}
${HEBCAL} 4 2012 > hebcal-test3.out


: ${DIFF=diff}
: ${srcdir=.}
${DIFF} ${srcdir}/hebcal-test3.ok hebcal-test3.out
result=$?

exit $result

# hebcal ends here
